# Generated by Django 4.2.6 on 2023-11-06 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cat",
            field=models.ManyToManyField(
                through="recipes.RecipeCategory",
                to="recipes.category",
                verbose_name="Категории",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(upload_to="photos/", verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="recipecategory",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recipes.category"
            ),
        ),
    ]
