# Generated by Django 4.2.6 on 2023-11-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_cat_alter_recipe_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name="Фото"),
        ),
    ]
